language: ruby

install:
  - bundle install --jobs 3 --retry 3
  - nvm install 10
  - node -v
  - npm i -g yarn
  - yarn
script: 
- bundle exec rake db:create:all 
- bundle exec rake db:migrate RAILS_ENV=test 
- bundle exec rails webpacker:compile
- rails test test/models/funcionario_test.rb
- rails test test/models/morador_test.rb
- rails test test/models/encomenda_test.rb
- bundle exec cucumber


services:
- postgresql